import jwt

token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc1NDYwODIxMSwianRpIjoiM2M3Zjg0NzUtNzEyZi00NjQxLWFlYTctNDRkODRhNDY3ODA2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6MSwibmJmIjoxNzU0NjA4MjExLCJleHAiOjE3NTQ2MzcwMTEsInJvbGUiOiJzdXBlcl9hZG1pbiIsImVtYWlsIjoiYWRtaW5AcHJhemRuaWt2ZG9tLmt6IiwibmFtZSI6Ilx1MDQxZVx1MDQzYlx1MDQ0Y1x1MDQzM1x1MDQzMCBcdTA0MThcdTA0MzJcdTA0MzBcdTA0M2RcdTA0M2VcdTA0MzJcdTA0MzAifQ._ptX7zTmp0L4aQCRJAzjxnIMb8QqfTTdi86-lelEaGI"
payload = jwt.decode(token, options={"verify_signature": False})
print(payload)